# Generated by Django 5.2.4 on 2025-09-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
