FROM python:slim
WORKDIR "./app"
COPY . .
# RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install -r requirements.txt
RUN apt-get update && apt-get install -y gdal-bin libgdal-dev
EXPOSE 8000
RUN python3 manage.py makemigrations
RUN python3 manage.py migrate
# CMD ["python3","manage.py","runserver","0.0.0.0:8000"]