version: '3.8'

services:
  django:
    build: 
      context: .
      dockerfile: dockerfile

    command: sh -c "python manage.py makemigrations && python manage.py migrate && echo \"from django.contrib.auth import get_user_model;User = get_user_model();User.objects.filter(email='ankamsaiteja27@gmail.com').exists() or User.objects.create_superuser(email='ankamsaiteja27@gmail.com',password= '123')\" | python manage.py shell && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    depends_on:
      - celery
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/1

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--port", "6379"]
    depends_on:
      - postgres

  celery:
    build: 
      context: .
      dockerfile: dockerfile
    command: celery -A server worker --loglevel=info
    volumes:
      - .:/app
    # env_file:
    #   - .env
    depends_on:
      - redis
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: rides_db
      POSTGRES_USER: rides_user
      POSTGRES_PASSWORD: rides_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: