version: '3.8'

services:
  django:
    build: 
      context: .
      dockerfile: dockerfile

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    depends_on:
      - celery
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/1

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--port", "6379"]

  celery:
    build: 
      context: .
      dockerfile: dockerfile
    command: celery -A server worker --loglevel=info
    volumes:
      - .:/app
    # env_file:
    #   - .env
    depends_on:
      - redis