# Generated by Django 5.2.4 on 2025-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
